"""Architecture diagram generator — produces Mermaid and Markdown diagrams."""

from typing import Any


class DiagramGenerator:
    def generate(self, spec: dict) -> str:
        components = spec.get("components", [])
        app_name = spec.get("app_name", "Application")
        style = spec.get("style", "microservices")

        sections = [
            self._header(app_name, style),
            self._mermaid_diagram(components),
            self._component_details(components),
            self._data_flow(components),
        ]
        return "\n\n".join(sections)

    def _header(self, name: str, style: str) -> str:
        return f"""# {name} — Architecture

**Style:** {style}

This diagram was auto-generated by [Archon](https://github.com/Nortaq-PlayNexus/archon)."""

    def _mermaid_diagram(self, components: list[dict]) -> str:
        lines = ["```mermaid", "graph TB"]
        node_map = {}

        for i, comp in enumerate(components):
            node_id = f"n{i}"
            node_map[comp["name"]] = node_id
            tech = comp.get("technology", "")
            ntype = comp.get("type", "")
            label = f"{comp['name']}\\n{tech}"
            shape = self._node_shape(ntype)
            lines.append(f"    {node_id}{shape[0]}{label}{shape[1]}")

        for comp in components:
            source = node_map.get(comp["name"])
            for dep in comp.get("dependencies", []):
                target = node_map.get(dep)
                if source and target:
                    lines.append(f"    {source} --> {target}")

        style_map = {
            "gateway": "#4A90D9",
            "service": "#50C878",
            "database": "#FFB347",
            "cache": "#FF6B6B",
            "queue": "#DDA0DD",
            "storage": "#87CEEB",
            "cdn": "#98FB98",
            "function": "#FFD700",
        }

        for comp in components:
            node_id = node_map.get(comp["name"])
            color = style_map.get(comp.get("type", ""), "#CCCCCC")
            if node_id:
                lines.append(f"    style {node_id} fill:{color},stroke:#333,stroke-width:2px")

        lines.append("```")
        return "\n## System Diagram\n\n" + "\n".join(lines)

    def _node_shape(self, ntype: str) -> tuple[str, str]:
        shapes = {
            "gateway": ("([", "])"),
            "service": ("[", "]"),
            "database": ("((", "))"),
            "cache": ("((", "))"),
            "queue": ("[[", "]]"),
            "storage": ("[", "]"),
            "cdn": (">", "]"),
            "function": ("{", "}"),
        }
        return shapes.get(ntype, ("[", "]"))

    def _component_details(self, components: list[dict]) -> str:
        lines = ["## Components\n"]
        lines.append("| Component | Type | Technology | Purpose | Ports |")
        lines.append("|-----------|------|-----------|---------|-------|")
        for c in components:
            ports = ", ".join(str(p) for p in c.get("ports", [])) or "—"
            lines.append(
                f"| {c['name']} | {c.get('type', '—')} | {c.get('technology', '—')} "
                f"| {c.get('purpose', '—')} | {ports} |"
            )
        return "\n".join(lines)

    def _data_flow(self, components: list[dict]) -> str:
        lines = ["## Data Flow\n"]
        for c in components:
            deps = c.get("dependencies", [])
            if deps:
                for dep in deps:
                    lines.append(f"1. **{c['name']}** → **{dep}** ({c.get('purpose', 'request')})")
        if len(lines) == 1:
            lines.append("No inter-component dependencies detected.")
        return "\n".join(lines)
