"""Repo exporter — packages output as a GitHub-ready repository."""

from pathlib import Path
from typing import Any


class RepoExporter:
    def export(self, spec: dict, output_path: Path):
        self._write_file(output_path / ".gitignore", self._gitignore())
        self._write_file(output_path / "LICENSE", self._license())
        self._write_file(output_path / "CONTRIBUTING.md", self._contributing())
        self._write_file(output_path / "SECURITY.md", self._security())
        self._write_file(output_path / ".github" / "PULL_REQUEST_TEMPLATE.md", self._pr_template())

    def _write_file(self, path: Path, content: str):
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            f.write(content)

    def _gitignore(self) -> str:
        return """# Generated by Archon
__pycache__/
*.py[cod]
.env
.env.local
node_modules/
dist/
build/
*.log
.DS_Store
Thumbs.db
"""

    def _license(self) -> str:
        return """MIT License

Copyright (c) 2026 PlayNexus

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

    def _contributing(self) -> str:
        return """# Contributing

Thank you for considering contributing to this project.

## How to Contribute

1. Fork the repository
2. Create a feature branch (`git checkout -b feature/amazing-feature`)
3. Commit your changes (`git commit -m 'Add amazing feature'`)
4. Push to the branch (`git push origin feature/amazing-feature`)
5. Open a Pull Request

## Development

```bash
cp .env.example .env
docker compose up -d
```

## Code Style

- Follow the existing code conventions
- Write meaningful commit messages
- Add tests for new features
"""

    def _security(self) -> str:
        return """# Security Policy

## Reporting a Vulnerability

If you discover a security vulnerability, please report it responsibly:

1. **Do NOT** open a public GitHub issue
2. Email security details to the maintainers
3. Allow time for a fix before public disclosure

## Supported Versions

| Version | Supported |
|---------|-----------|
| 1.0.x   | Yes       |
| < 1.0   | No        |
"""

    def _pr_template(self) -> str:
        return """## Description

Brief description of changes.

## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Testing

- [ ] Tests pass locally
- [ ] New tests added (if applicable)

## Checklist

- [ ] Code follows project style
- [ ] Self-review completed
- [ ] Documentation updated
"""
