"""Repo exporter — packages output as a GitHub-ready repository."""

from pathlib import Path


class RepoExporter:
    def export(self, spec: dict, output_path: Path):
        self._write_file(output_path / ".gitignore", self._gitignore())
        self._write_file(output_path / "LICENSE", self._license())
        self._write_file(output_path / "CONTRIBUTING.md", self._contributing())
        self._write_file(output_path / "SECURITY.md", self._security())
        self._write_file(output_path / ".github" / "PULL_REQUEST_TEMPLATE.md", self._pr_template())
        self._write_file(output_path / ".github" / "workflows" / "ci.yml", self._ci_yml())
        self._write_file(output_path / ".github" / "dependabot.yml", self._dependabot_yml())
        self._write_file(
            output_path / ".github" / "ISSUE_TEMPLATE" / "bug_report.md",
            self._bug_report_template(),
        )
        self._write_file(output_path / "Makefile", self._makefile())

        if (output_path / "Dockerfile").exists():
            self._write_file(output_path / ".dockerignore", self._dockerignore())

    def _write_file(self, path: Path, content: str):
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            f.write(content)

    def _gitignore(self) -> str:
        return """# Generated by Archon
__pycache__/
*.py[cod]
.env
.env.local
node_modules/
dist/
build/
*.log
.DS_Store
Thumbs.db
"""

    def _license(self) -> str:
        return """MIT License

Copyright (c) 2026 PlayNexus

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

    def _contributing(self) -> str:
        return """# Contributing

Thank you for considering contributing to this project.

## How to Contribute

1. Fork the repository
2. Create a feature branch (`git checkout -b feature/amazing-feature`)
3. Commit your changes (`git commit -m 'Add amazing feature'`)
4. Push to the branch (`git push origin feature/amazing-feature`)
5. Open a Pull Request

## Development

```bash
cp .env.example .env
docker compose up -d
```

## Code Style

- Follow the existing code conventions
- Write meaningful commit messages
- Add tests for new features
"""

    def _security(self) -> str:
        return """# Security Policy

## Reporting a Vulnerability

If you discover a security vulnerability, please report it responsibly:

1. **Do NOT** open a public GitHub issue
2. Email security details to the maintainers
3. Allow time for a fix before public disclosure

## Supported Versions

| Version | Supported |
|---------|-----------|
| 1.0.x   | Yes       |
| < 1.0   | No        |
"""

    def _pr_template(self) -> str:
        return """## Description

Brief description of changes.

## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Testing

- [ ] Tests pass locally
- [ ] New tests added (if applicable)

## Checklist

- [ ] Code follows project style
- [ ] Self-review completed
- [ ] Documentation updated
"""

    def _ci_yml(self) -> str:
        return """name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 2>/dev/null || true
          pip install -e . 2>/dev/null || true
      - name: Lint
        run: |
          pip install ruff 2>/dev/null || true
          ruff check . 2>/dev/null || echo "Ruff not configured"
      - name: Test
        run: |
          pytest 2>/dev/null || echo "No tests configured"
"""

    def _dependabot_yml(self) -> str:
        return """version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
"""

    def _bug_report_template(self) -> str:
        return """---
name: Bug Report
about: Report a bug to help us improve
title: "[BUG] "
labels: bug
assignees: ''
---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. 
2. 
3. 

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment:**
- OS: [e.g., Ubuntu 22.04]
- Python Version: [e.g., 3.12]
- Node Version: [e.g., 20] (if applicable)

**Additional context**
Add any other context about the problem here.
"""

    def _dockerignore(self) -> str:
        return """# Generated by Archon
.git
.gitignore
.env
.env.local
node_modules
__pycache__
*.pyc
.pytest_cache
.mypy_cache
.ruff_cache
dist
build
*.egg-info
venv
.venv
README.md
LICENSE
CONTRIBUTING.md
SECURITY.md
.github
Makefile
"""

    def _makefile(self) -> str:
        return """# Generated by Archon
.PHONY: help install dev test lint format run docker-build docker-run clean

help: ## Show this help
\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\\033[36m%-20s\\033[0m %s\\n", $$1, $$2}'

install: ## Install production dependencies
\tpip install -r requirements.txt 2>/dev/null || true

dev: ## Install dev dependencies
\tpip install -r requirements.txt -r requirements-dev.txt 2>/dev/null || true
\tnpm install 2>/dev/null || true

test: ## Run tests
\tpytest 2>/dev/null || echo "No tests configured"

lint: ## Run linter
\truff check . 2>/dev/null || echo "Ruff not configured"

format: ## Format code
\truff format . 2>/dev/null || echo "Ruff not configured"

run: ## Run the application
\tpython -m archon 2>/dev/null || echo "Configure entry point"

docker-build: ## Build Docker image
\tdocker build -t app .

docker-run: ## Run Docker container
\tdocker compose up -d

clean: ## Clean build artifacts
\tfind . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
\tfind . -type f -name '*.pyc' -delete 2>/dev/null || true
\trm -rf dist build *.egg-info .pytest_cache .mypy_cache .ruff_cache 2>/dev/null || true
"""
