"""Infrastructure code generator — Terraform, Docker, Docker Compose."""



class InfraGenerator:
    def generate_terraform(self, spec: dict) -> str:
        infra = spec.get("infrastructure", {})
        cloud = infra.get("cloud", "aws")
        compute = infra.get("compute", "ecs")
        db_service = infra.get("database_service", "rds")
        cache_service = infra.get("cache_service", "elasticache")
        app_name = spec.get("app_name", "app").lower().replace(" ", "-").replace("_", "-")

        if cloud == "aws":
            return self._aws_terraform(app_name, compute, db_service, cache_service)
        elif cloud == "gcp":
            return self._gcp_terraform(app_name, compute)
        elif cloud == "azure":
            return self._azure_terraform(app_name, compute)
        return self._aws_terraform(app_name, compute, db_service, cache_service)

    def _aws_terraform(self, name: str, compute: str, db: str, cache: str) -> str:
        return f"""# Generated by Archon — https://github.com/Nortaq-PlayNexus/archon
# AWS Infrastructure

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = var.aws_region
}}

variable "aws_region" {{
  default = "us-east-1"
}}

variable "app_name" {{
  default = "{name}"
}}

# VPC
resource "aws_vpc" "main" {{
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  tags = {{
    Name = var.app_name
  }}
}}

resource "aws_subnet" "public" {{
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.1.0/24"
  availability_zone       = "${{var.aws_region}}a"
  map_public_ip_on_launch = true
  tags = {{ Name = "${{var.app_name}}-public" }}
}}

resource "aws_subnet" "private" {{
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.2.0/24"
  availability_zone = "${{var.aws_region}}b"
  tags = {{ Name = "${{var.app_name}}-private" }}
}}

# Security Group
resource "aws_security_group" "app" {{
  vpc_id = aws_vpc.main.id
  name   = "${{var.app_name}}-sg"

  ingress {{
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}
}}

# RDS PostgreSQL
resource "aws_db_instance" "main" {{
  identifier     = "${{var.app_name}}-db"
  engine         = "postgres"
  engine_version = "16"
  instance_class = "db.t3.micro"

  allocated_storage     = 20
  max_allocated_storage = 100
  storage_encrypted     = true

  db_name  = "appdb"
  username = "dbadmin"
  password = var.db_password

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.db.id]

  backup_retention_period = 7
  skip_final_snapshot     = true
}}

resource "aws_db_subnet_group" "main" {{
  name       = "${{var.app_name}}-db-subnet"
  subnet_ids = [aws_subnet.private.id]
}}

resource "aws_security_group" "db" {{
  vpc_id = aws_vpc.main.id
  name   = "${{var.app_name}}-db-sg"

  ingress {{
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [aws_security_group.app.id]
  }}
}}

variable "db_password" {{
  sensitive = true
}}

# ElastiCache Redis
resource "aws_elasticache_cluster" "main" {{
  cluster_id      = "${{var.app_name}}-cache"
  engine          = "redis"
  node_type       = "cache.t3.micro"
  num_cache_nodes = 1
  port            = 6379

  security_group_ids = [aws_security_group.cache.id]
  subnet_group_name  = aws_elasticache_subnet_group.main.name
}}

resource "aws_elasticache_subnet_group" "main" {{
  name       = "${{var.app_name}}-cache-subnet"
  subnet_ids = [aws_subnet.private.id]
}}

resource "aws_security_group" "cache" {{
  vpc_id = aws_vpc.main.id
  name   = "${{var.app_name}}-cache-sg"

  ingress {{
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = [aws_security_group.app.id]
  }}
}}

# ECS Cluster (Fargate)
resource "aws_ecs_cluster" "main" {{
  name = var.app_name
}}

resource "aws_ecs_service" "app" {{
  name            = "${{var.app_name}}-service"
  cluster         = aws_ecs_cluster.main.id
  desired_count   = 2
  launch_type     = "FARGATE"
  task_definition = aws_ecs_task_definition.app.arn

  network_configuration {{
    subnets         = [aws_subnet.private.id]
    security_groups = [aws_security_group.app.id]
  }}
}}

resource "aws_ecs_task_definition" "app" {{
  family                   = var.app_name
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "256"
  memory                   = "512"

  container_definitions = jsonencode([
    {{
      name      = "app"
      image     = "${{aws_caller_identity.current.account_id}}.dkr.ecr.${{var.aws_region}}.amazonaws.com/${{var.app_name}}:latest"
      portMappings = [{{ containerPort = 8000, hostPort = 8000 }}]
      environment = [
        {{ name = "DATABASE_URL", value = "postgresql://dbadmin:${{var.db_password}}@${{aws_db_instance.main.address}}:5432/appdb" }},
        {{ name = "REDIS_URL", value = "redis://${{aws_elasticache_cluster.main.cache_nodes.0.address}}:6379" }},
      ]
      logConfiguration = {{
        logDriver = "awslogs"
        options = {{
          awslogs-group         = "/ecs/${{var.app_name}}"
          awslogs-region        = var.aws_region
          awslogs-stream-prefix = "ecs"
        }}
      }}
    }}
  ])
}}

data "aws_caller_identity" "current" {{}}

# Outputs
output "db_endpoint" {{
  value = aws_db_instance.main.address
}}

output "cache_endpoint" {{
  value = aws_elasticache_cluster.main.cache_nodes.0.address
}}

output "ecs_cluster" {{
  value = aws_ecs_cluster.main.name
}}
"""

    def _gcp_terraform(self, name: str, compute: str) -> str:
        return f"""# Generated by Archon — https://github.com/Nortaq-PlayNexus/archon
# GCP Infrastructure

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = "~> 5.0"
    }}
  }}
}}

provider "google" {{
  project = var.project_id
  region  = var.region
}}

variable "project_id" {{ type = string }}
variable "region" {{ default = "us-central1" }}

resource "google_cloud_run_service" "app" {{
  name     = "{name}"
  location = var.region

  template {{
    spec {{
      containers {{
        image = "gcr.io/${{var.project_id}}/{name}:latest"
        ports {{
          container_port = 8000
        }}
      }}
    }}
  }}
}}

resource "google_sql_database_instance" "main" {{
  name             = "{name}-db"
  database_version = "POSTGRES_16"
  region           = var.region

  settings {{
    tier = "db-f1-micro"
  }}
}}

resource "google_redis_instance" "cache" {{
  name           = "{name}-cache"
  memory_size_gb = 1
  region         = var.region
}}
"""

    def _azure_terraform(self, name: str, compute: str) -> str:
        return f"""# Generated by Archon — https://github.com/Nortaq-PlayNexus/archon
# Azure Infrastructure

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }}
  }}
}}

provider "azurerm" {{
  features {{}}
}}

resource "azurerm_resource_group" "main" {{
  name     = "{name}-rg"
  location = "East US"
}}

resource "azurerm_container_group" "app" {{
  name                = "{name}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  os_type             = "Linux"

  container {{
    name   = "app"
    image  = "{name}:latest"
    cpu    = "1.0"
    memory = "1.5"

    ports {{
      port     = 8000
      protocol = "TCP"
    }}
  }}
}}
"""

    def generate_docker_compose(self, spec: dict) -> str:
        components = spec.get("components", [])
        app_name = spec.get("app_name", "app").lower().replace(" ", "-").replace("_", "-")
        lines = [
            "# Generated by Archon — https://github.com/Nortaq-PlayNexus/archon",
            f"# {app_name} — Docker Compose",
            "",
            "services:",
        ]

        for comp in components:
            ctype = comp.get("type", "service")
            name = comp["name"]
            tech = comp.get("technology", "python:3.12-slim")
            ports = comp.get("ports", [])

            lines.append(f"  {name}:")
            lines.append(f"    image: {tech}")

            if ctype == "service":
                lines.append("    build:")
                lines.append("      context: .")
                lines.append("      dockerfile: Dockerfile")
            elif ctype in ("database", "cache"):
                lines.append("    restart: unless-stopped")

            if ports:
                port_mapping = f"{ports[0]}:{ports[0]}"
                lines.append("    ports:")
                lines.append(f'      - "{port_mapping}"')

            if ctype == "database":
                lines.append("    environment:")
                lines.append("      POSTGRES_DB: appdb")
                lines.append("      POSTGRES_USER: dbadmin")
                lines.append("      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}")
                lines.append("    volumes:")
                lines.append("      - pgdata:/var/lib/postgresql/data")

            if ctype == "cache":
                lines.append("    command: redis-server --appendonly yes")
                lines.append("    volumes:")
                lines.append("      - redisdata:/data")

            deps = comp.get("dependencies", [])
            if deps:
                lines.append("    depends_on:")
                for dep in deps:
                    lines.append(f"      - {dep}")

            lines.append("")

        has_db = any(c.get("type") == "database" for c in components)
        has_cache = any(c.get("type") == "cache" for c in components)
        if has_db or has_cache:
            lines.append("volumes:")
            if has_db:
                lines.append("  pgdata:")
            if has_cache:
                lines.append("  redisdata:")

        return "\n".join(lines) + "\n"

    def generate_dockerfile(self, spec: dict) -> str:
        components = spec.get("components", [])
        app_tech = "python:3.12-slim"
        for c in components:
            if c.get("type") == "service":
                app_tech = c.get("technology", app_tech)
                break

        if "python" in app_tech:
            return self._python_dockerfile()
        elif "node" in app_tech or "next" in app_tech:
            return self._node_dockerfile()
        elif "go" in app_tech:
            return self._go_dockerfile()
        elif "rust" in app_tech:
            return self._rust_dockerfile()
        return self._python_dockerfile()

    def _python_dockerfile(self) -> str:
        return """# Generated by Archon — https://github.com/Nortaq-PlayNexus/archon
FROM python:3.12-slim AS base

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

    def _node_dockerfile(self) -> str:
        return """# Generated by Archon — https://github.com/Nortaq-PlayNexus/archon
FROM node:20-alpine AS base

WORKDIR /app
COPY package*.json .
RUN npm ci

COPY . .
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
"""

    def _go_dockerfile(self) -> str:
        return """# Generated by Archon — https://github.com/Nortaq-PlayNexus/archon
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/server .

FROM alpine:3.19
COPY --from=builder /app/server /server
EXPOSE 8080
CMD ["/server"]
"""

    def _rust_dockerfile(self) -> str:
        return """# Generated by Archon — https://github.com/Nortaq-PlayNexus/archon
FROM rust:1.77-slim AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build --release
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/server /server
EXPOSE 8080
CMD ["/server"]
"""
