"""Database schema generator — produces SQL DDL from architecture spec."""

from typing import Any


class SchemaGenerator:
    TYPE_MAP = {
        "UUID": "UUID",
        "STRING": "VARCHAR(255)",
        "TEXT": "TEXT",
        "INTEGER": "INTEGER",
        "BIGINT": "BIGINT",
        "FLOAT": "DOUBLE PRECISION",
        "BOOLEAN": "BOOLEAN",
        "TIMESTAMP": "TIMESTAMPTZ",
        "TIMESTAMPTZ": "TIMESTAMPTZ",
        "JSON": "JSONB",
        "JSONB": "JSONB",
    }

    def generate(self, spec: dict) -> str:
        tables = spec.get("database_schema", {}).get("tables", [])
        if not tables:
            return "-- No tables defined in the architecture spec.\n"

        sections = [
            "-- Generated by Archon — https://github.com/Nortaq-PlayNexus/archon",
            "-- Database Schema\n",
        ]

        for table in tables:
            sections.append(self._create_table(table))

        return "\n".join(sections)

    def _create_table(self, table: dict) -> str:
        name = table["name"]
        columns = table.get("columns", [])

        col_defs = []
        pks = []

        for col in columns:
            parts = [f"    {col['name']}"]
            col_type = col.get("type", "VARCHAR(255)").upper()
            parts.append(self.TYPE_MAP.get(col_type, col_type))
            if col.get("primary_key"):
                parts.append("PRIMARY KEY")
                pks.append(col["name"])
            elif not col.get("nullable", True):
                parts.append("NOT NULL")
            if col.get("unique"):
                parts.append("UNIQUE")
            col_defs.append(" ".join(parts))

        lines = [f"CREATE TABLE IF NOT EXISTS {name} ("]
        lines.append(",\n".join(col_defs))
        lines.append(");\n")

        for col in columns:
            if col.get("unique") and not col.get("primary_key"):
                lines.append(
                    f"CREATE UNIQUE INDEX IF NOT EXISTS idx_{name}_{col['name']} "
                    f"ON {name} ({col['name']});"
                )

        lines.append("")
        return "\n".join(lines)
