"""Database schema generator — produces SQL DDL from architecture spec."""


class SchemaGenerator:
    TYPE_MAP = {
        "UUID": "UUID",
        "STRING": "VARCHAR(255)",
        "TEXT": "TEXT",
        "INTEGER": "INTEGER",
        "BIGINT": "BIGINT",
        "FLOAT": "DOUBLE PRECISION",
        "BOOLEAN": "BOOLEAN",
        "TIMESTAMP": "TIMESTAMPTZ",
        "TIMESTAMPTZ": "TIMESTAMPTZ",
        "JSON": "JSONB",
        "JSONB": "JSONB",
    }

    MYSQL_TYPE_MAP = {
        "UUID": "CHAR(36)",
        "STRING": "VARCHAR(255)",
        "TEXT": "TEXT",
        "INTEGER": "INT",
        "BIGINT": "BIGINT",
        "FLOAT": "DOUBLE",
        "BOOLEAN": "TINYINT(1)",
        "TIMESTAMP": "DATETIME",
        "TIMESTAMPTZ": "DATETIME",
        "JSON": "JSON",
        "JSONB": "JSON",
    }

    SQLITE_TYPE_MAP = {
        "UUID": "TEXT",
        "STRING": "TEXT",
        "TEXT": "TEXT",
        "INTEGER": "INTEGER",
        "BIGINT": "INTEGER",
        "FLOAT": "REAL",
        "BOOLEAN": "INTEGER",
        "TIMESTAMP": "TEXT",
        "TIMESTAMPTZ": "TEXT",
        "JSON": "TEXT",
        "JSONB": "TEXT",
    }

    def generate(self, spec: dict, dialect: str = "postgresql") -> str:
        tables = spec.get("database_schema", {}).get("tables", [])
        if not tables:
            return "-- No tables defined in the architecture spec.\n"

        sections = [
            "-- Generated by Archon — https://github.com/Nortaq-PlayNexus/archon",
            f"-- Database Schema (dialect: {dialect})\n",
        ]

        for table in tables:
            sections.append(self._create_table(table, dialect))

        return "\n".join(sections)

    def _get_type_map(self, dialect: str) -> dict[str, str]:
        if dialect == "mysql":
            return self.MYSQL_TYPE_MAP
        elif dialect == "sqlite":
            return self.SQLITE_TYPE_MAP
        return self.TYPE_MAP

    def _create_table(self, table: dict, dialect: str = "postgresql") -> str:
        name = table["name"]
        columns = table.get("columns", [])
        type_map = self._get_type_map(dialect)

        col_defs = []
        pks = []
        foreign_keys = []

        for col in columns:
            parts = [f"    {col['name']}"]
            col_type = col.get("type", "VARCHAR(255)").upper()
            parts.append(type_map.get(col_type, col_type))
            if col.get("primary_key"):
                parts.append("PRIMARY KEY")
                pks.append(col["name"])
            elif not col.get("nullable", True):
                parts.append("NOT NULL")
            if col.get("unique"):
                parts.append("UNIQUE")
            if col.get("autoincrement") and dialect == "mysql":
                parts.append("AUTO_INCREMENT")
            col_defs.append(" ".join(parts))

            if col.get("references"):
                ref = col["references"]
                ref_table = ref.get("table", "")
                ref_col = ref.get("column", "id")
                on_delete = ref.get("on_delete", "CASCADE")
                foreign_keys.append(
                    f"    FOREIGN KEY ({col['name']}) REFERENCES {ref_table}({ref_col}) ON DELETE {on_delete}"
                )

        if len(pks) > 1 and dialect == "postgresql":
            col_defs.append(f"    PRIMARY KEY ({', '.join(pks)})")
        elif dialect == "mysql" and len(pks) > 1:
            col_defs.append(f"    PRIMARY KEY ({', '.join(pks)})")

        for fk in foreign_keys:
            col_defs.append(fk)

        lines = [f"CREATE TABLE IF NOT EXISTS {name} ("]
        lines.append(",\n".join(col_defs))
        lines.append(");\n")

        if dialect == "postgresql":
            for col in columns:
                if col.get("unique") and not col.get("primary_key"):
                    lines.append(
                        f"CREATE UNIQUE INDEX IF NOT EXISTS idx_{name}_{col['name']} "
                        f"ON {name} ({col['name']});"
                    )
        elif dialect == "mysql":
            for col in columns:
                if col.get("unique") and not col.get("primary_key"):
                    lines.append(
                        f"CREATE UNIQUE INDEX idx_{name}_{col['name']} ON {name} ({col['name']});"
                    )
        elif dialect == "sqlite":
            for col in columns:
                if col.get("unique") and not col.get("primary_key"):
                    lines.append(
                        f"CREATE UNIQUE INDEX IF NOT EXISTS idx_{name}_{col['name']} "
                        f"ON {name} ({col['name']});"
                    )

        lines.append("")
        return "\n".join(lines)
